export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnnksVysdK4ZGsuTtduLV
oJghyspUwCGkNLGB0EDnCKzxCTUmbqP2ELMuUn3kxAJNcEuvPrmn0Xz0FLClPhgG
lZM02CyuLJKZe3rKsRjzyXIb0ohq7nYd4MOt+k8HT45Df3JSBWgOku3vpsHdUvRR
8Rp8MPiMG0UE/1BdTo/yg4fUtUZ+9KCjM+pcaTn2aJs7+7zj2DdRp+GlgODNwUZZ
br+z3djACSuPdNqfz8XQ5QcTwaeFu4XqqsGqCOtZzNeBmDMIXPSuqyZ2NXHWhWiY
yx/Hh3E0u4BxfS+NMD6EXdPypJ59zB7rpBDLxkKGabjD9lsXDOcLcDjMIcMW65M8
jwIDAQAB
-----END PUBLIC KEY-----
`;